'''
Model's hyper-params & consts
'''

# Params
MIN_ELLIPSE_RADIUS = 5
INITIAL_SHAPE_MAX_VAR = 10000
RESIZED_PIXELS_AMOUNT = 2500
MUTATION_PROBABILITY = 0.01
MUTATION_AMOUNT = 0.1
GENERATION_POPULATION = 50
CROSSOVER_POPULATION = 20
MAX_ITERATIONS = 9999999999
MAX_SECONDS = 300
NUMBER_OF_SHAPES = 100
INITIAL_FIXED_STATES = 10
INITIAL_RANDOM_LOCATION_STATES = 30
INITIAL_TRULY_RANDOM_STATES = GENERATION_POPULATION - INITIAL_FIXED_STATES - INITIAL_RANDOM_LOCATION_STATES

# Consts
MAX_PIXEL_DISTANCE = 442
MAX_COLOR = 255